name: Deployment
on:
  push:
    branches:
      - master
      - dev
env: # any environmnet varaible place here is available for any job in the workflow
 MONGODB_DB_NAME: Cluster0
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.wkfi46r.mongodb.net
      MONGODB_USERNAME: kodjovi
      MONGODB_PASSWORD: ty3O9VSwMz5zQjrn
      PORT: 8080
    #environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: "echo MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
        
